BUILD_DIR = build
SOURCE_DIR = .

include $(N64_INST)/include/n64.mk

N64_ROM_TITLE = "Elite - The New Kind"
N64_ROM_SAVETYPE = eeprom16k
N64_ROM_REGIONFREE = true

SRCS = \
	n64_main.c \
	n64_gfx.c \
	n64_input.c \
	n64_sound.c \
	n64_file.c \
	n64_font.c \
	n64_spritedata.c \
	elite.c \
	docked.c \
	intro.c \
	missions.c \
	options.c \
	pilot.c \
	planet.c \
	random.c \
	shipdata.c \
	shipface.c \
	space.c \
	stars.c \
	swat.c \
	threed.c \
	trade.c \
	vector.c

OBJS = $(SRCS:%.c=$(BUILD_DIR)/%.o)

CFLAGS += -DPLATFORM_N64 -I. -Wno-error

# Filesystem assets
WAV_SRCS = launch.wav crash.wav dock.wav gameover.wav pulse.wav hitem.wav \
           explode.wav ecm.wav missile.wav hyper.wav incom1.wav incom2.wav \
           beep.wav boop.wav
WAV64_TARGETS = $(WAV_SRCS:%.wav=filesystem/%.wav64)

all: elite_newkind.z64

filesystem:
	@mkdir -p filesystem

filesystem/%.wav64: %.wav | filesystem
	@echo "    [AUDIO] $<"
	$(N64_AUDIOCONV) --wav-resample 16000 --wav-mono -o $@ $<

filesystem/newkind.cfg: newkind.cfg | filesystem
	cp $< $@
filesystem/newscan.cfg: newscan.cfg | filesystem
	cp $< $@
filesystem/scanner.bmp: scanner.bmp | filesystem
	cp $< $@

FILESYSTEM_DEPS = $(WAV64_TARGETS) filesystem/newkind.cfg filesystem/newscan.cfg filesystem/scanner.bmp

$(BUILD_DIR)/elite_newkind.dfs: $(FILESYSTEM_DEPS)
elite_newkind.z64: $(BUILD_DIR)/elite_newkind.elf $(BUILD_DIR)/elite_newkind.dfs
$(BUILD_DIR)/elite_newkind.elf: $(OBJS)

clean:
	rm -rf $(BUILD_DIR) filesystem elite_newkind.z64

.PHONY: all clean
