/**
 *
 * Elite - The New Kind.
 *
 * N64 port: Asset declarations for embedded data.
 *
 **/

#ifndef N64_ASSETS_H
#define N64_ASSETS_H

#include <stdint.h>

/* Embedded 8x8 bitmap font (ASCII 32-127, 96 glyphs x 8 bytes each) */
extern const uint8_t n64_font_8x8[];

/* Embedded sprite data (generated by tools/convert_assets.py) */
#define N64_NUM_SPRITE_SLOTS 14
extern const uint8_t * const n64_sprite_data[N64_NUM_SPRITE_SLOTS];
extern const int n64_sprite_widths[N64_NUM_SPRITE_SLOTS];
extern const int n64_sprite_heights[N64_NUM_SPRITE_SLOTS];

#endif
