#!/usr/bin/env python3
"""
Elite - The New Kind (N64 port)

Converts extracted .sprite files into a C source file with embedded
sprite pixel data as const uint8_t arrays.

Sprite file format: 2-byte LE width, 2-byte LE height, then raw 8-bit
indexed pixel data (width * height bytes).

The generated arrays are indexed by the alg_data.h constants:
  BLAKE=0, ECM=2, ELITETXT=5, FRONTV=6, GRNDOT=7,
  MISSILE_G=8, MISSILE_R=9, MISSILE_Y=10, REDDOT=11, SAFE=12
"""

import os
import struct
import sys

# Sprite definitions: (alg_data.h index, filename, expected_width, expected_height)
SPRITES = [
    (0,  "blake.sprite",     98, 130),
    (2,  "ecm.sprite",       12,  16),
    (5,  "elitetxt.sprite", 163,  37),
    (6,  "frontv.sprite",    81,  12),
    (7,  "grndot.sprite",    10,  10),
    (8,  "missile_g.sprite", 12,  10),
    (9,  "missile_r.sprite", 12,  10),
    (10, "missile_y.sprite", 12,  10),
    (11, "reddot.sprite",    10,  10),
    (12, "safe.sprite",      12,  16),
]

# Total slots needed (0..13, matching alg_data.h which goes up to THEME=13)
NUM_SLOTS = 14


def read_sprite(path):
    """Read a .sprite file and return (width, height, pixel_data)."""
    with open(path, "rb") as f:
        data = f.read()
    if len(data) < 4:
        raise ValueError(f"{path}: file too small")
    w = struct.unpack_from("<H", data, 0)[0]
    h = struct.unpack_from("<H", data, 2)[0]
    pixels = data[4:]
    expected = w * h
    if len(pixels) != expected:
        raise ValueError(
            f"{path}: expected {expected} pixels ({w}x{h}), got {len(pixels)}"
        )
    return w, h, pixels


def format_c_array(name, data, cols=16):
    """Format a byte array as a C const uint8_t array."""
    lines = []
    lines.append(f"static const uint8_t {name}[] = {{")
    for i in range(0, len(data), cols):
        chunk = data[i:i+cols]
        hex_vals = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"\t{hex_vals},")
    lines.append("};")
    return "\n".join(lines)


def main():
    # Determine paths relative to this script
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_dir = os.path.dirname(script_dir)
    sprite_dir = os.path.join(project_dir, "data", "sprites")
    output_path = os.path.join(project_dir, "n64_spritedata.c")

    # Allow overriding paths via command line
    if len(sys.argv) > 1:
        sprite_dir = sys.argv[1]
    if len(sys.argv) > 2:
        output_path = sys.argv[2]

    print(f"Sprite directory: {sprite_dir}")
    print(f"Output file:      {output_path}")

    # Read all sprites
    sprite_data = {}  # index -> (w, h, pixels)
    for idx, filename, exp_w, exp_h in SPRITES:
        path = os.path.join(sprite_dir, filename)
        if not os.path.exists(path):
            print(f"  WARNING: {filename} not found, skipping index {idx}")
            continue
        w, h, pixels = read_sprite(path)
        if w != exp_w or h != exp_h:
            print(
                f"  WARNING: {filename} dimensions {w}x{h} "
                f"differ from expected {exp_w}x{exp_h}"
            )
        sprite_data[idx] = (w, h, pixels)
        print(f"  [{idx:2d}] {filename:20s} {w:4d}x{h:<4d} ({len(pixels)} bytes)")

    # Generate C source
    out = []
    out.append("/**")
    out.append(" * Elite - The New Kind.")
    out.append(" *")
    out.append(" * N64 port: Auto-generated sprite data.")
    out.append(" * Generated by tools/convert_assets.py - do not edit by hand.")
    out.append(" */")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("")
    out.append(f"#define N64_NUM_SPRITE_SLOTS {NUM_SLOTS}")
    out.append("")

    # Emit individual pixel arrays
    for idx, filename, _, _ in SPRITES:
        if idx not in sprite_data:
            continue
        w, h, pixels = sprite_data[idx]
        name = os.path.splitext(filename)[0] + "_pixels"
        out.append(f"/* [{idx}] {filename} ({w}x{h}) */")
        out.append(format_c_array(name, pixels))
        out.append("")

    # Emit the lookup table for pixel data pointers
    out.append("/* Sprite pixel data pointers, indexed by alg_data.h constants */")
    out.append(f"const uint8_t * const n64_sprite_data[{NUM_SLOTS}] = {{")
    for i in range(NUM_SLOTS):
        if i in sprite_data:
            # Find the filename for this index
            fname = None
            for idx, fn, _, _ in SPRITES:
                if idx == i:
                    fname = fn
                    break
            name = os.path.splitext(fname)[0] + "_pixels"
            out.append(f"\t{name},  /* [{i}] */")
        else:
            out.append(f"\t0,  /* [{i}] unused */")
    out.append("};")
    out.append("")

    # Emit width array
    out.append(f"const int n64_sprite_widths[{NUM_SLOTS}] = {{")
    for i in range(NUM_SLOTS):
        if i in sprite_data:
            w = sprite_data[i][0]
            out.append(f"\t{w},  /* [{i}] */")
        else:
            out.append(f"\t0,  /* [{i}] unused */")
    out.append("};")
    out.append("")

    # Emit height array
    out.append(f"const int n64_sprite_heights[{NUM_SLOTS}] = {{")
    for i in range(NUM_SLOTS):
        if i in sprite_data:
            h = sprite_data[i][1]
            out.append(f"\t{h},  /* [{i}] */")
        else:
            out.append(f"\t0,  /* [{i}] unused */")
    out.append("};")
    out.append("")

    # Write output
    with open(output_path, "w") as f:
        f.write("\n".join(out) + "\n")

    print(f"\nGenerated {output_path} ({os.path.getsize(output_path)} bytes)")


if __name__ == "__main__":
    main()
